export default {
  name: 'portableText',
  type: 'array',
  title: 'Portable Text',
  of: [
    {
      type: 'block',
      styles: [
        { title: 'Normal', value: 'normal' },
        { title: 'H1', value: 'h1' },
        { title: 'H2', value: 'h2' },
        { title: 'H3', value: 'h3' },
        { title: 'H4', value: 'h4' },
        { title: 'H5', value: 'h5' },
        { title: 'H1 Bold', value: 'h1Bold' },
        { title: 'H2 Bold', value: 'h2Bold' },
        { title: 'H3 Bold', value: 'h3Bold' },
        { title: 'H4 Bold', value: 'h4Bold' },
        { title: 'H5 Bold', value: 'h5Bold' },
        { title: 'Lead', value: 'lead' },
        { title: 'Lead Bold', value: 'leadBold' },
        { title: 'Lead Underline', value: 'leadUnderline' },
        { title: 'Caption', value: 'caption' },
        { title: 'Caption Bold', value: 'captionBold' },
        { title: 'Body', value: 'body' },
        { title: 'Body Bold', value: 'bodyBold' },
        { title: 'Body Italic', value: 'bodyItalic' },
        { title: 'Body Underline', value: 'bodyUnderline' },
        { title: 'Body Uppercase', value: 'bodyUppercase' },
        { title: 'Small', value: 'small' },
        { title: 'Small Bold', value: 'smallBold' },
        { title: 'Small Italic', value: 'smallItalic' },
        { title: 'Small Underline', value: 'smallUnderline' },
        { title: 'Small Uppercase', value: 'smallUppercase' },
        { title: 'Tiny', value: 'tiny' },
        { title: 'Tiny Bold', value: 'tinyBold' },
        { title: 'Tiny Italic', value: 'tinyItalic' },
        { title: 'Tiny Underline', value: 'tinyUnderline' },
        { title: 'Tiny Uppercase', value: 'tinyUppercase' },
      ],
    },
    {
      type: 'image',
    },
    {
      type: 'image-quote-block',
    },
  ],
};
